services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq
    command: rabbitmq-server
    ports:
      - 5672:5672
    expose:
      - "5672"
      - "15672"
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "5672"]
      interval: 10s
      timeout: 10s
      retries: 5

networks:
  tic-tac:
    name: tic-tac
    driver: bridge

volumes:
  pgdata:
